name: aplication_noticias
description: "App de noticias"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  http: ^0.13.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - imagenes/noticiero.jpg
  - imagenes/noticia_clubOlimpo.jpg
  - imagenes/noticia2.jpg
  - imagenes/noticia3.jpg
  - imagenes/noticia4.jpg
  - imagenes/noticia5.jpg
  - imagenes/noticia6.jpg
  - imagenes/noticia7.jpg
  