name: aplication_noticias
description: "App de noticias"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  http: ^1.3.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.2.1 
  cached_network_image: ^3.2.3 # o la versión más reciente


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - images/
  